Added class creation
scalableinternetservices/sail-in-jails pull request #12
Opened 2019-10-26 16:42 UTC by joelwdav

doesn't include the stuff from the sign in branch.

path '/classes' is the page to add and remove the classes.

2019-10-26 18:16 UTC, anton5798 commented on config/routes.rb~
> +Rails.application.routes.draw do
can remove this ~ file

2019-10-26 18:22 UTC, anton5798 requested changes
Generally looks good! A couple of comments 

1. Remove ~ file
2. Could you please rename the controller/view to be courses_controller to be consistent with the model name?
3. Also I think the link that appears after the creation of class is incorrect 
4. We might also want the show method in the controller so that the new link actually works
5. Remove the testing db files. They should be .gitignored, and I'm not sure why they are being added.

2019-10-26 23:55 UTC, joelwdav commented
I changed the routes and controllers but I didn't do anything with the links because I don't know what I'm doing with them yet. I put them there just to make sure things were working properly.

2019-10-27 00:03 UTC, anton5798 approved these changes
Looks good! Still minor details to be fixed, but we'll do that once we have more functionality

2019-10-27 00:55 UTC, merged